server:
  port: 8080

spring:
  datasource:
    # 1. Base de datos principal (GOV_CONNECT_DB)
    primary:
      jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=GOV_CONNECT_DB;encrypt=true;trustServerCertificate=true
      username: sia_connect
      password: SiaConnect2026!
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    # 2. Base de datos secundaria (ERP_DB)
    # erp:
      #jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=ERP_DB;encrypt=true;trustServerCertificate=true
      #username: sia_connect
      #password: SiaConnect2026!
      #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info